export const GenderOptions = ['Male', 'Female', 'Other'] as const;

export const IdentificationTypes = [
	'Birth Certificate',
	"Driver's License",
	'Medical Insurance Card/Policy',
	'Military ID Card',
	'National Identity Card',
	'Passport',
	'Resident Alien Card (Green Card)',
	'Social Security Card',
	'State ID Card',
	'Student ID Card',
	'Voter ID Card',
] as const;

export const Doctors = [
	{
		image: 'images/dr-green.png',
		name: 'John Green',
	},
	{
		image: 'images/dr-cameron.png',
		name: 'Leila Cameron',
	},
	{
		image: 'images/dr-livingston.png',
		name: 'David Livingston',
	},
	{
		image: 'images/dr-peter.png',
		name: 'Evan Peter',
	},
	{
		image: 'images/dr-powell.png',
		name: 'Jane Powell',
	},
	{
		image: 'images/dr-remirez.png',
		name: 'Alex Ramirez',
	},
	{
		image: 'images/dr-lee.png',
		name: 'Jasmine Lee',
	},
	{
		image: 'images/dr-cruz.png',
		name: 'Alyana Cruz',
	},
	{
		image: 'images/dr-sharma.png',
		name: 'Hardik Sharma',
	},
];

export const DummyAppointments = [
	{
		patient: 'Jessica Jones',
		primaryPhysician: 'John Green',
		appointmentReason: 'Monthly checkup',
		schedule: new Date('2024-09-12T14:30:00'),
		status: 'pending',
		note: 'After noon will be great!',
	},
	{
		patient: 'Walter White',
		primaryPhysician: 'Leila Cameron',
		appointmentReason: 'Routine examination',
		schedule: new Date('2024-09-13T10:00:00'),
		status: 'pending',
		note: 'Prefer early morning.',
	},
	{
		patient: 'Skyler White',
		primaryPhysician: 'David Livingston',
		appointmentReason: 'Blood test',
		schedule: new Date('2024-09-15T15:00:00'),
		status: 'pending',
		note: 'Afternoon is best.',
	},
	{
		patient: 'Hank Schrader',
		primaryPhysician: 'Evan Peter',
		appointmentReason: 'Follow-up visit',
		schedule: new Date('2024-09-16T11:00:00'),
		status: 'pending',
		note: 'Late morning would work.',
	},
	{
		patient: 'Marie Schrader',
		primaryPhysician: 'Jane Powell',
		appointmentReason: 'Annual checkup',
		schedule: new Date('2024-09-17T13:30:00'),
		status: 'pending',
		note: 'After noon is preferable.',
	},
	{
		patient: 'Saul Goodman',
		primaryPhysician: 'Alex Ramirez',
		appointmentReason: 'Consultation',
		schedule: new Date('2024-09-18T16:00:00'),
		status: 'pending',
		note: 'Evening would be ideal.',
	},
	{
		patient: 'Gus Fring',
		primaryPhysician: 'Jasmine Lee',
		appointmentReason: 'Health check',
		schedule: new Date('2024-09-19T09:00:00'),
		status: 'pending',
		note: 'Early morning is best.',
	},
	{
		patient: 'Tuco Salamanca',
		primaryPhysician: 'Alyana Cruz',
		appointmentReason: 'Medication review',
		schedule: new Date('2024-09-20T14:00:00'),
		status: 'pending',
		note: 'Post-lunch slot preferred.',
	},
	{
		patient: 'Mike Ehrmantraut',
		primaryPhysician: 'Hardik Sharma',
		appointmentReason: 'Wellness check',
		schedule: new Date('2024-09-21T12:30:00'),
		status: 'pending',
		note: 'Midday appointment works.',
	},
	{
		patient: 'Jane Margolis',
		primaryPhysician: 'John Green',
		appointmentReason: 'General checkup',
		schedule: new Date('2024-09-22T10:30:00'),
		status: 'pending',
		note: 'Late morning is fine.',
	},
	{
		patient: 'Tyrus Kitt',
		primaryPhysician: 'Leila Cameron',
		appointmentReason: 'Routine follow-up',
		schedule: new Date('2024-09-23T11:15:00'),
		status: 'pending',
		note: 'Prefer before noon.',
	},
	{
		patient: 'Jack Welker',
		primaryPhysician: 'David Livingston',
		appointmentReason: 'Specialist consultation',
		schedule: new Date('2024-09-24T13:00:00'),
		status: 'pending',
		note: 'Early afternoon preferred.',
	},
	{
		patient: 'Lydia Rodarte-Quayle',
		primaryPhysician: 'Evan Peter',
		appointmentReason: 'Health screening',
		schedule: new Date('2024-09-25T15:30:00'),
		status: 'pending',
		note: 'Post-lunch slot works.',
	},
	{
		patient: 'Hector Salamanca',
		primaryPhysician: 'Jane Powell',
		appointmentReason: 'Routine check',
		schedule: new Date('2024-09-26T09:45:00'),
		status: 'pending',
		note: 'Early morning is preferable.',
	},
	{
		patient: 'Gale Boetticher',
		primaryPhysician: 'Alex Ramirez',
		appointmentReason: 'Quarterly checkup',
		schedule: new Date('2024-09-27T14:45:00'),
		status: 'pending',
		note: 'Afternoon works best.',
	},
	{
		patient: 'Andrea Cantillo',
		primaryPhysician: 'Jasmine Lee',
		appointmentReason: 'Medication review',
		schedule: new Date('2024-09-28T11:30:00'),
		status: 'pending',
		note: 'Late morning is ideal.',
	},
	{
		patient: 'Carmen Molina',
		primaryPhysician: 'Alyana Cruz',
		appointmentReason: 'Consultation',
		schedule: new Date('2024-09-29T16:30:00'),
		status: 'pending',
		note: 'Evening slot is preferred.',
	},
	{
		patient: 'Francesca Liddy',
		primaryPhysician: 'Hardik Sharma',
		appointmentReason: 'Checkup',
		schedule: new Date('2024-09-30T12:00:00'),
		status: 'pending',
		note: 'Midday appointment is good.',
	},
	{
		patient: 'David Rodriguez',
		primaryPhysician: 'John Green',
		appointmentReason: 'Health assessment',
		schedule: new Date('2024-10-01T13:00:00'),
		status: 'pending',
		note: 'Post-lunch time is ideal.',
	},
	{
		patient: 'Eileen McLaren',
		primaryPhysician: 'Leila Cameron',
		appointmentReason: 'Routine examination',
		schedule: new Date('2024-10-02T10:00:00'),
		status: 'pending',
		note: 'Morning slot works best.',
	},
	{
		patient: 'Leonel Rivas',
		primaryPhysician: 'David Livingston',
		appointmentReason: 'Follow-up visit',
		schedule: new Date('2024-10-03T14:00:00'),
		status: 'pending',
		note: 'Afternoon appointment preferred.',
	},
	{
		patient: 'Juan Bolsa',
		primaryPhysician: 'Evan Peter',
		appointmentReason: 'Medication check',
		schedule: new Date('2024-10-04T09:30:00'),
		status: 'pending',
		note: 'Early morning is good.',
	},
	{
		patient: 'Tio Salamanca',
		primaryPhysician: 'Jane Powell',
		appointmentReason: 'General health review',
		schedule: new Date('2024-10-05T15:00:00'),
		status: 'pending',
		note: 'Late afternoon slot works.',
	},
	{
		patient: 'Kim Wexler',
		primaryPhysician: 'Alex Ramirez',
		appointmentReason: 'Consultation',
		schedule: new Date('2024-10-06T11:00:00'),
		status: 'pending',
		note: 'Late morning preferred.',
	},
];
